dist: xenial
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.9
      env: TOXENV=flake8

    # Django 2.0
    - python: 3.6
      env: TOXENV=py36-django20
    - python: 3.7
      env: TOXENV=py37-django20
    - python: 3.8
      env: TOXENV=py38-django20
    - python: 3.9
      env: TOXENV=py39-django20

    # Django 2.1
    - python: 3.6
      env: TOXENV=py36-django21
    - python: 3.7
      env: TOXENV=py37-django21
    - python: 3.8
      env: TOXENV=py38-django21
    - python: 3.9
      env: TOXENV=py39-django21

    # Django 2.2
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.8
      env: TOXENV=py38-django22
    - python: 3.9
      env: TOXENV=py39-django22

    # Django 3.0
    - python: 3.6
      env: TOXENV=py36-django30
    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.8
      env: TOXENV=py38-django30
    - python: 3.9
      env: TOXENV=py39-django30

    # Django 3.1
    - python: 3.6
      env: TOXENV=py36-django31
    - python: 3.7
      env: TOXENV=py37-django31
    - python: 3.8
      env: TOXENV=py38-django31
    - python: 3.9
      env: TOXENV=py39-django31

    # Django 3.2
    - python: 3.6
      env: TOXENV=py36-django32
    - python: 3.7
      env: TOXENV=py37-django32
    - python: 3.8
      env: TOXENV=py38-django32
    - python: 3.9
      env: TOXENV=py39-django32

    # Django main
    - python: 3.8
      env: TOXENV=py38-djangomain
    - python: 3.9
      env: TOXENV=py39-djangomain

  allow_failures:
    - env: TOXENV=py38-djangomain
    - env: TOXENV=py39-djangomain

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install codecov
  - codecov
